### ISSUE TITLE
[sources] remove sources when a worker is removed

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger.html#7660]
We currently work around the fact that it can be difficult to remove sources in our redux store. We should bite the bullet and properly clean up the redux store when a worker is removed

- thread's sources are removed
- thread can no longer be selected
- maybe we need to select a new location if we're currently viewing a source for that worker

**Comment by AnshulMalik** [comment]
Do we have a hook for when the worker is removed?
How do we know if worker is removed?

**Comment by AnshulMalik** [comment]
`updateWorkers` is called just once that's when setting up the application. So we are assuming that workers will not be removed while the debugger is running?
This looks fine for when we open the debugger, we should not have extra workers. I was thinking of removing the sources as soon as some worker is removed.

**Comment by jasonLaster** [comment]
it is also called when the worker list changes
https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/events.js#L118-L122
