### ISSUE TITLE
Make ObjectInspector accessible to keyboard when focusable.

### ISSUE THREAD

**Issue by yzen** [firefox-devtools/debugger.html#7874]
At the moment even when ObjectInspector is set to be focusable, focus handling does not work very well for focusable elements that are inside the TreeNode items of its internal Tree. To be consistent with other tools in the toolbox (primarily markup inspector) it'd be ideal to allow to explicitly activate/deactivate a TreeNode for keyboard navigation using Enter[Space]/Escape respectively. Similarly how it happens in the markup view.

**Comment by jasonLaster** [comment]
@yzen i'm re-opening this as it failed  browser_webconsole_object_in_sidebar_keyboard_nav.js.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=9677d62d2832352c2eab422171d641b7c97c7aa6&selectedJob=229134680

I can land the commit with a revert in MC so you can fix the patch in MC and land it there.
Also, I noticed some weirdness here with the source tree and space bar and enter not toggling directories or selecting a source.

**Comment by yzen** [comment]
@jasonLaster , hopefully this will do it.
