### ISSUE TITLE
Space added between the characters in shortcuts on macOS

### ISSUE THREAD

**Issue by bamanczak** [firefox-devtools/debugger.html#7892]
Formatted Keyboard shortcuts on MacOS have a space added between characters
![image](https://user-images.githubusercontent.com/8224947/52326487-236d5f80-29e9-11e9-8fac-f9e1ef85c1fd.png)

However on MacOS it's a standard to format shortcuts without any space
![image](https://user-images.githubusercontent.com/8224947/52327286-dc349e00-29eb-11e9-8d88-c68c9deafd54.png)

The fix needs to be implemented in src/utils/text.js (formatKeyShortcut function).

**Comment by fvsch** [comment]
It might be worth exploring if we can set a font-family which renders the command and shift signs better. Can be a bit hard to do in a way that works in Firefox and Chrome, though.

According to https://caniuse.com/#search=system-ui, maybe this could work?
`font-family: system-ui, -apple-system, sans-serif;`

We should be able to construct selectors that only target macOS, too, though I'm not sure the selectors would be the same for the Debugger in Firefox and as a standalone tool.
