### ISSUE TITLE
Consider removing postcss-bidirection

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger.html#7941]
Using postcss-bidirection creates issues in the CSS codebase because it adds specificity to selectors, e.g. this `0.1.0` selector:

```
.my-component {
  margin-inline-start: 10px;
}
```

becomes a `0.2.1` selector:

```
html[dir="rtl"] .my-component {
  margin-right: 10px;
}
```

This creates small specificity wars, with traces that can be seen in the CSS codebase.
So it would be cleaner to use the native support for direction-relative margin/padding/border/inset, if possible.

Turns out Chrome 69, released 2018-09-04 (current stable is 72) introduced support for all the relevant properties. A few are noted in the MDN compat data, but others are missing, so I filed an issue:
https://github.com/mdn/browser-compat-data/issues/3443

My tests in Chrome 69 are pretty conclusive.

Now, Debugger may also support other browsers for its launchpad mode. So I looked at Edge and Safari:

- Latest Edge: nope, no support.
- Safari 12: only supports `-webkit-(margin|padding|border)-(start|end)`

The good news is that autoprefixer is already adding those webkit prefixes.
The main limit for WebKit would be the lack of an equivalent to `inset-inline-(start|end)`, which we are using in half a dozen places in the CSS codebase.

I guess it depends on the browser support we want.

**Comment by jasonLaster** [comment]
I think Chrome+Firefox support is sufficient. I'd be fine removing support for bidirection.

**Comment by fvsch** [comment]
Just noting here that the postcss-bidirection dep is in devtools-launchpad.
Doesn't stop us from removing it in postcss.config.js, but it may require some follow-up.

```
debugger.html@0.6.0 ~/workspace/debugger.html
└─┬ devtools-launchpad@0.0.148
  └── postcss-bidirection@2.6.0 
```
