### ISSUE TITLE
File appears twice when doing a file search

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger.html#7971]
**Steps to reproduce**
1. Go to https://nchevobbe.github.io/demo/console-test-app.html
1. Open the debugger
1. Hit <kbd>Cmd + P</kbd> to open the file search
1. Type `App.js`

**Expected results**

I see the `App.js` file

**Actual results**

There's 2 `App.js` files, with similar paths

<img width="450" alt="image" src="https://user-images.githubusercontent.com/578107/52849708-fc620c80-3111-11e9-89d9-43d48da2c07f.png">

**Comment by darkwing** [comment]
Could this be why?

<img width="1058" alt="maybe" src="https://user-images.githubusercontent.com/46655/52871515-d76c9a00-310f-11e9-8205-611d65924d0e.png">

**Comment by nchevobbe** [comment]
yeah, must be that I guess
