### ISSUE TITLE
Storage is not loading on IPv6 local site

### ISSUE THREAD

**Issue by chpio** [firefox-devtools/debugger.html#7980]
Hi,

when i load up a local site via IPv6 address <http://[::1]/> the cookie tab isn't showing anything. 
![screenshot from 2019-02-18 11-12-00](https://user-images.githubusercontent.com/545659/52943805-3a5b6c80-336e-11e9-9ca2-33429f79051f.png)
![screenshot from 2019-02-18 11-12-52](https://user-images.githubusercontent.com/545659/52943808-3c253000-336e-11e9-9bb3-3423b793ee18.png)

**Comment by jasonLaster** [comment]
@chpio please file this bug in http://bugzilla.mozilla.org/
