### ISSUE TITLE
Debugger doesn't stop at breakpoint in browser.js (Android)

### ISSUE THREAD

**Issue by buttercookie42** [firefox-devtools/debugger.html#8002]
STR:
1. Install a current Fennec Nightly and enable USB debugging.
2. Connect with WebIDE, open the debugger, open chrome://content/browser.js
3. If WebIDE remembered your last session, clear any pre-existing breakpoints.
4. Set a new breakpoint at the [first line of onLocationChange](https://searchfox.org/mozilla-central/rev/4587d146681b16ff9878a6fdcba53b04f76abe1d/mobile/android/chrome/content/browser.js#4625).
5. Navigate to any page.

Expected:
The breakpoint is hit.

Actual:
Nothing happens. If however you terminate the current debugging session (leave the breakpoint intact!) and then start a new session (for some other reason you might need to re-toggle the debugging switch in Fennec to get it to reappear in WebIDE), the automatically restored breakpoint will be working fine. Any freshly added breakpoints browser.js on the other hand still don't work. Disabling and then re-enabling the restored breakpoint will cause it to stop working likewise.
Breakpoints added in other files (e.g. jar://components/SessionStore.js) on the other hand work normally.

**Comment by jasonLaster** [comment]
Hi @buttercookie42, could you file this issue in bugzilla?

**Comment by buttercookie42** [comment]
Bugzilla said to file it here :-), but certainly.

**Comment by jasonLaster** [comment]
haha sorry for the confusion

**Comment by jasonLaster** [comment]
Also, please link the bugzilla bug here so i can track it

**Comment by buttercookie42** [comment]
[Bug 1529332](https://bugzilla.mozilla.org/show_bug.cgi?id=1529332).
